// Created using the image.py script written by Patrick Hughes. He's a pretty cool guy.
// Script then modified by Aron Cedercrantz to output a (NS|UI)Image category.
//
// DO NOT EDIT THIS FILE. 
//
// This file is automatically generated. Any changes may be overwritten the next time images.py is invoked.

@interface UIImage (PRIAppImages)

+ (instancetype)pri_settings;

@end
