// Created using the image.py script written by Patrick Hughes. He's a pretty cool guy.
// Script then modified by Aron Cedercrantz to output a (NS|UI)Image category.
//
// DO NOT EDIT THIS FILE. 
//
// This file is automatically generated. Any changes may be overwritten the next time images.py is invoked.

#import "UIImage+PRIAppImages.h"

@implementation UIImage (PRIAppImages)

+ (instancetype)pri_sourceDropbox { id image = [[self class] imageNamed:@"source-dropbox"]; ZAssert(image, @"Image source-dropbox not found"); return image; }
+ (instancetype)pri_sourceWebsite { id image = [[self class] imageNamed:@"source-website"]; ZAssert(image, @"Image source-website not found"); return image; }
+ (instancetype)pri_navPrintQueueTemplate { id image = [[self class] imageNamed:@"nav-print-queue-template"]; ZAssert(image, @"Image nav-print-queue-template not found"); return image; }
+ (instancetype)pri_navSettingsTemplate { id image = [[self class] imageNamed:@"nav-settings-template"]; ZAssert(image, @"Image nav-settings-template not found"); return image; }
+ (instancetype)pri_sourcePhotoLibrary { id image = [[self class] imageNamed:@"source-photo-library"]; ZAssert(image, @"Image source-photo-library not found"); return image; }

@end
